package me.jbduncan;

/**
 * A simple token class. These are generated by Lexer and consumed by Parser.
 */
public record Token(TokenType type, String text) {
  @Override
  public String toString() {
    return text;
  }
}
